1. Write a Python function to check if a string is a palindrome. (String from user input)

In [17]:
def isPalindrome(s: str)->bool:
    s.lower().replace(" ","")
    return s==s[::-1]

word = input("Enter a word to check weather it is palindrom or not :")
print(f"The word {word} is Palindrome ?:",isPalindrome(word))

Enter a word to check weather it is palindrom or not : mam


The word mam is Palindrome ?: True


2. Given a list of numbers, use list comprehension to create a list of their squares.

In [18]:
def ListComprehension(l1:list):
    return [x**2 for x in l1]

l1 = list(map(int,input("enter the numbers separated by spaces :").split()))
print(ListComprehension(l1))

enter the numbers separated by spaces : 1 2 3 4 5 6 7 8 9


[1, 4, 9, 16, 25, 36, 49, 64, 81]


3. Create a DataFrame of 5 students with their marks and find who scored more than 80.

In [27]:
# pip install pandas

In [21]:
import pandas as pd
Students = {
    "Name":["Chandan G","Shreyas","Animesh","Preeti","Shrilakshmi"],
    "Marks" :[88,76,69,87,88]
}

Students_DataFrame = pd.DataFrame(Students)

Students_DataFrame

Name  Marks
0    Chandan G     88
1      Shreyas     76
2      Animesh     69
3       Preeti     87
4  Shrilakshmi     88

In [26]:
filter_Df = Students_DataFrame[Students_DataFrame["Marks"]>80]
filter_Df

Name  Marks
0    Chandan G     88
3       Preeti     87
4  Shrilakshmi     88

4. Create a 5x5 array with random integers between 1 and 100.

In [31]:
# pip install numpy

In [30]:
import numpy as np

mat = np.random.randint(1,101,size=(5,5))
print(mat)

[[ 83  90 100  46  81]
 [ 11  93  21  81  73]
 [  3   6  80  81  83]
 [ 13  23  42  75  67]
 [ 16  28  28  25  66]]


5 . Create a DataFrame of products with columns: Product Name, Price, Category.
    Add a new column - Discounted Price = 90% of Price.
    Filter and show products cheaper than 500.

In [37]:
import pandas as pd
ProductInfo = {
    "Product Name":["Laptop", "Smartphone", "Headphones", "Coffee Maker", "Desk Chair",
    "Refrigerator", "Microwave Oven", "Smartwatch", "Bookshelf", "Gaming Console",
    "Washing Machine", "Office Desk", "Bluetooth Speaker", "Air Conditioner", "Table Lamp"
    ],
    "Price":[55000, 25000, 3000, 7000, 12000,
    40000, 150, 1000, 500, 35000,
    30000, 18000, 567, 450, 2500
    ],
    "Category" : ["Electronics", "Electronics", "Electronics", "Home Appliances", "Furniture",
    "Home Appliances", "Home Appliances", "Electronics", "Furniture", "Electronics",
    "Home Appliances", "Furniture", "Electronics", "Home Appliances", "Furniture"
    ]
}

ProductInfo_Df = pd.DataFrame(ProductInfo)
ProductInfo_Df

Product Name  Price         Category
0              Laptop  55000      Electronics
1          Smartphone  25000      Electronics
2          Headphones   3000      Electronics
3        Coffee Maker   7000  Home Appliances
4          Desk Chair  12000        Furniture
5        Refrigerator  40000  Home Appliances
6      Microwave Oven    150  Home Appliances
7          Smartwatch   1000      Electronics
8           Bookshelf    500        Furniture
9      Gaming Console  35000      Electronics
10    Washing Machine  30000  Home Appliances
11        Office Desk  18000        Furniture
12  Bluetooth Speaker    567      Electronics
13    Air Conditioner    450  Home Appliances
14         Table Lamp   2500        Furniture

In [38]:
# there 2 ways we can do this one is iterative approach using comprehension other one is vector operation 
# both works but the vector operation is much faster than iterative approach
# ProductInfo_Df["Discounted Price"] = [(x*90)/100 for x in ProductInfo_Df["Price"]]  
ProductInfo_Df["Discounted Price"] = ProductInfo_Df["Price"]*0.9
ProductInfo_Df

Product Name  Price         Category  Discounted Price
0              Laptop  55000      Electronics           49500.0
1          Smartphone  25000      Electronics           22500.0
2          Headphones   3000      Electronics            2700.0
3        Coffee Maker   7000  Home Appliances            6300.0
4          Desk Chair  12000        Furniture           10800.0
5        Refrigerator  40000  Home Appliances           36000.0
6      Microwave Oven    150  Home Appliances             135.0
7          Smartwatch   1000      Electronics             900.0
8           Bookshelf    500        Furniture             450.0
9      Gaming Console  35000      Electronics           31500.0
10    Washing Machine  30000  Home Appliances           27000.0
11        Office Desk  18000        Furniture           16200.0
12  Bluetooth Speaker    567      Electronics             510.3
13    Air Conditioner    450  Home Appliances             405.0
14         Table Lamp   2500        Furniture            2250.0

In [40]:
ProductInfo_Df_filter = ProductInfo_Df[ProductInfo_Df["Discounted Price"]<=500]
ProductInfo_Df_filter

Product Name  Price         Category  Discounted Price
6    Microwave Oven    150  Home Appliances             135.0
8         Bookshelf    500        Furniture             450.0
13  Air Conditioner    450  Home Appliances             405.0